### ISSUE TITLE
Feature request: Retrieving parts of cubes / reports

### ISSUE THREAD

**Issue by mzunhammer** [MicroStrategy/mstrio#1]
Hi Scott,
I've started playing around with the mstrio API-interface for R this week. Great job. Very clear and easy use, no problems so far, except for one issue: When the requested cube/report are too large, download becomes impossible. It would be helpful to pre-select table columns and/or to "filter" by rows via the API. Do you plan implementing such a feature ?
Cheers, Matthias

**Comment by drzamich** [comment]
Hello @mzunhammer. Thank you veru much for your feedback. The mstrio version `11.1.4.25` introduced `Cube` and `Report` classes, which have the `apply_filters()` method. As its name suggests, using it will filter the dataset, therefore limiting its size.
