### ISSUE TITLE
Cube$New : Error in response$cookies$value[[2]] : subscript out of bounds

### ISSUE THREAD

**Issue by ismailmuller** [MicroStrategy/mstrio#12]
Hello,
I have the following error when trying to run the following `mstrio::Cube$new(connection = mstr_conn, cube_id)`
```
Error in response$cookies$value[[2]] : subscript out of bounds
```
This is due to the `mstrio:::cube_info(mstr_conn, cube_id)` which gives `response$cookies` of class data.frame with a single row (meaning there can't be a 2nd value and hence the error is inevitable). 
Is this due to the version of MSTR (11.2) we have that is different from the package mstrio (11.3)?

sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

packageVersion("mstrio")
‘11.3.0.1’

MSTR Status:
{"upSince":1624122853531,"upTime":509996545,"upTimeText":"141 Hours 39 Minutes 56 seconds","webVersion":"11.1.0.22546J","baseUri":"my_company/MicroStrategyLibrary/api/","iServerVersion":"11.2.0100.38862"}

**Comment by urszulajaczewska** [comment]
Hi @ismailmuller, seems like a bug, we will investigate it.
We'd appreciate it if you can check if the same setup works for someone else with higher R version or different mstrio version,  or with different server version if possible.

**Comment by urszulajaczewska** [comment]
Hi @ismailmuller, this issue is fixed with new mstrio release.
