### ISSUE TITLE
Dataset$create() raises:  Error in if(iserver_code == ISERVER_CODE_TIMEOUT)  Argument is of length zero

### ISSUE THREAD

**Issue by Banjio** [MicroStrategy/mstrio#14]
# The starting situation

Using the tutorial https://cran.r-project.org/web/packages/mstrio/vignettes/mstrio.html i wanted to test the different functionality of the MSTRIO package. Unfortunately the creation of a cube fails. However, it is not problematic that the creation fails but how it fails. The following code,

```R
conn = getMstrioCon()
dat <- iris[1:50, ]

# note: column names in MicroStrategy cannot have a period (".")
names(dat) <- gsub("[[:punct:]]", "_", names(dat))

# this creates the dataset, and returns the dataset object, which you can use to update the dataset later
my_dataset <- mstrio::Dataset$new(connection=conn, name="IRIS_Upload")

# add one or more tables to the dataset
my_dataset$add_table(name = "IRIS_Upload",
					 data_frame = dat,
					 update_policy = "add")
my_dataset$create(auto_upload = FALSE,
				  auto_publish = FALSE)
my_dataset$update(auto_publish = FALSE)
# https://community.microstrategy.com/s/article/KB310757-The-error-quot-At-least-one-of-the-tables-in-EMMA-cube?language=en_US
my_dataset$publish()
```

Is a slightly modified version of the tutorial snippet (I split up the creation of the cube to investigate which part of the cube creation is failing).  The publish function fails and raises the error: Error in if(iserver_code == ISERVER_CODE_TIMEOUT)  Argument is of length zero. 

# Cause of the error. 

Obviously this error is caused by an if statement. More specificially an if statement where ```NULL``` is compared with another value. This comparison can be found inside ```utils-errors.R::detect_error_subclass```. 

# Fixing the error 

This can be fixed with the following snippet: 
```R
detect_error_subclass <- function(http_code, error_code, iserver_code = NULL) {
  if (!is.null(iserver_code) && iserver_code == ISERVER_CODE_TIMEOUT) {
    return(MSTR_TIMEOUT_ERROR_CLASS)
  }
  else {
    return(NULL)
  }
}
```
This prevents the if condition from raising an error. In addition the ```utils-errors.R::gen_mstr_error function``` needs a slight modification so that ```sprintf``` is not used with a NULL value. Otherwise the error logged to stdout is "ERROR: <NA>" which is equally non saying than the original error. To fix this i used the following snippet: 

```R
gen_mstr_error <- function(response, custom_message) {
  http_code <- response$status_code
  content <- httr::content(response)
  error_code <- content$code
  iserver_code <- content$iServerCode
  server_message <- content$message
  ticket_id <- content$ticketId
  error_subclass <- detect_error_subclass(http_code, error_code, iserver_code)
  error_class <- ifelse(!is.null(error_subclass), c(error_subclass, MSTR_ERROR_CLASS), MSTR_ERROR_CLASS)
  iserver_code_char <- ifelse(is.null(iserver_code), "NULL", iserver_code)
  error_message <- sprintf("%s: %s (Ticket ID: %s, iServerCode: %s)", error_code, server_message, ticket_id, iserver_code_char)
  full_message <- ifelse(!is.null(custom_message), sprintf("%s\n%s", custom_message, error_message), error_message)
  gen_custom_error(.subclass = error_class, message = full_message, http_code = http_code, error_code = error_code, iserver_code = iserver_code, server_message = server_message, ticket_id = ticket_id, custom_message = custom_message)
}
```  
# Why was this neccessary?

After fixing this i finally get an error message that atleast tells me what the problem with cube creation could be. The endpoint publish_status() has the following problem: 
```
HTTP Error: 500 Internal Server Error
I-Server Error:
ERR001: [{"error code":"-2147213784","tableId":"DD3A52C311EC46BCC1460080EF856BB6","error message":"Refresh table fails when discovering data from data source."}] (Ticket ID: b73c6005932840d68d6af8755f7bec8e, iServerCode: NULL)
```
Which i now have to investigate further. 

It would be nice if you could fix the error handling or let me create a merge request to fix it. Furthermore the functions mentioned could need some refactoring because they have unused variables. 

Kind regards,

**Comment by urszulajaczewska** [comment]
Hi @Banjio, we will look into this and I'll update you as soon as possible.

**Comment by urszulajaczewska** [comment]
Hi @Banjio, we've further looked into this and decided that it's a good solution. We'll work on implementation.
Thank you :)

**Comment by urszulajaczewska** [comment]
Hi @Banjio we've fixed this issue in March release and improved error handling.

**Comment by Banjio** [comment]
Thank you all i really appreciate it
