### ISSUE TITLE
Consume Flat Files Directly into MSTR

### ISSUE THREAD

**Issue by brandonritchie** [MicroStrategy/mstrio#17]
It appears that there is no way to consume flat files (csv, JSON, geoJSON, etc.) into MSTR without first making it into a dataframe. Could this be a feature that is added to package?

**Comment by urszulajaczewska** [comment]
Hi @brandonritchie, can you specify what do you mean by:
- MSTR - RStudio directly, or MSTR Server?
- consuming flat files - have it as variable in RStudio or somehow save raw data into MSTR Server?

Do you mean you need a workflow of saving raw file into server or do you want to manipulate some data in RStudio without changing its 'character' into dataframe?

**Comment by brandonritchie** [comment]
Hi @urszulajaczewska, thank you for the reply! Yes MSTR server. I want to be able to essentially have the functionality of the file upload button within Microstrategy web, but accomplish it programmatically. I have a raw geojson file that I am fetching from an API request and I need to read it into a table in Microstrategy. Currently, if I understand correctly, the mstrio package only accepts R dataframes and this makes it difficult to consume a geojson file that has specific encodings for the geometry column.

**Comment by p-kowal** [comment]
Hi @brandonritchie The ETA for this request is still not determined by the PM. I am not expecting delivery of it soon, if ever. Thus I am closing this issue. Thanks for understanding.
