### ISSUE TITLE
Authentication mode unsupported?

### ISSUE THREAD

**Issue by kkadu** [MicroStrategy/mstrio#20]
MicroStrategy Library support SAML / OKTA auth but when I try using MicroStrategy mstrio in jupyter, the plugin only provides two options standard / ldap. How do we enable this option for SAML?

If it is not possible via jupyter, how to setup the auth in postman for SAML to use MicroStrategy Library API? I am getting an error for unsupported method / login failure when I select auth mode = 2.

**Comment by urszulajaczewska** [comment]
Hi @kkadu, there is no possibility to use SAML/OKTA in Jupyter connector and currently we don't plan to put it in our roadmap.
REST API only allows following authentication methods: Standard (1), Anonymous (8) or LDAP (16).
