### ISSUE TITLE
Supported version error

### ISSUE THREAD

**Issue by celiomsj** [MicroStrategy/mstrio#5]
Hi,

I'm getting version error when trying to connect.

```
# Error: This version of mstrio is only supported on MicroStrategy 11.1.0400 or higher.
#    Current Intelligence Server version: 11.1.1.22
#    Current MicroStrategy Web version: 11.1.1.25
```

Is it correct or am I misreading something?

**Comment by drzamich** [comment]
Hi @celiomsj - `11.1.0400` is meant `11.1.4` (cut the leading/trailing zeros), while your MicroStrategy installation is of version `11.1.1`.
